Add NeuralNetwork constructor to load from a trained .pt file
eric-heiden/tiny-differentiable-simulator pull request #1
Opened 2020-12-13 21:12 UTC by AiRuiChen

Tested: this code is tested to work w/ the MPC neural network (generated [here](https://github.com/uscresl/hybrid-sim-exp/tree/master/neural_mpc)) we used for the Laikago locomotion experiment.

2020-12-13 22:25 UTC, eric-heiden commented on CMakeLists.txt
> +        message("Torch include directories: ${TORCH_LIBRARIES}")
The variable corresponds to libraries, not include directories

2020-12-13 22:29 UTC, eric-heiden requested changes
Thanks for the PR! Could you address my comments, and also use `.cpp` as extension for the demo you implemented (like we have the other examples).

2020-12-13 22:29 UTC, eric-heiden commented on src/math/neural_network.hpp
> +            current[ci] = tds::where_gt(current[ci], zero, current[ci],
Is this change necessary?

2020-12-13 22:29 UTC, eric-heiden commented on src/math/neural_network.hpp
> +#if USE_TORCH
use `#ifdef USE_TORCH`

2020-12-13 22:29 UTC, eric-heiden commented on src/math/neural_network.hpp
> +#if USE_TORCH
use `#ifdef USE_TORCH`

2020-12-13 22:56 UTC, AiRuiChen commented on src/math/neural_network.hpp
> +            current[ci] = tds::where_gt(current[ci], zero, current[ci],
It's effectively the same. Reverted.

2020-12-15 05:04 UTC, AiRuiChen commented
Closing this as I will directly create a PR to the google-research repo

2020-12-15 05:04 UTC, closed without merging